definitions:
  db.Car:
    properties:
      base_color:
        type: string
      code:
        type: string
      col_code:
        type: string
      color:
        type: string
      country:
        type: string
      created_at:
        type: string
      id:
        type: string
      image:
        type: string
      interior_color:
        type: string
      model_name:
        type: string
      notes:
        type: string
      series_code:
        type: string
      series_name:
        type: string
      tampo:
        type: string
      updated_at:
        type: string
      wheel_type:
        type: string
      window_color:
        type: string
    type: object
  db.SearchResult:
    properties:
      code:
        type: string
      col_code:
        type: string
      id:
        type: string
      image:
        type: string
      model_name:
        type: string
      notes:
        type: string
      series_code:
        type: string
      series_name:
        type: string
    type: object
  routes.Error:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /cars:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Car'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/routes.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.Error'
      summary: Get all cars
  /search:
    get:
      parameters:
      - description: Query
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.SearchResult'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/routes.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.Error'
      summary: Search cars
swagger: "2.0"
